### ISSUE TITLE
organizar a estrutura de pastas

### ISSUE THREAD

**Issue by bruno3du** [screstani/drum-js#2]
Quanto maiores os projetos, maior é a necessidade de organizar as pastas, porque o volume de arquivos aumenta e fica fácil se perder. Além disso alguns sites dependem de uma estrutura para fazer o deploy do projeto, a netlify mesmo recomenda. Então a estrutura que costumo indicar é, criar uma pasta assets, dentro dela crie pastas para css, js, img e qualquer uma mais que forem necessárias. Se tiver dúvidas da pra procurar pelo modelo. Daí é só deixar cada tipo de arquivo na sua respectiva pasta

**Comment by screstani** [comment]
issue resolved
